version: '3.4'

services:
    stream:
        image: stream
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            NODE_ENV: development
        ports:
            - 5003:5003
            - 9229:9229
        command: ['node', '--inspect=0.0.0.0:9229', 'app.js']
